version: '3'
services:
  street-pothole-monitor-backend:
    build: .
    container_name: pothole-backend
    ports:
      - '8080:80'
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb+srv://root:root@cluster0.i8a2ejt.mongodb.net/
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
