version: '3'
services:
  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb+srv://root:root@cluster0.i8a2ejt.mongodb.net/
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
